# Generated by Django 4.2.5 on 2023-11-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_id_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_id",
            name="id",
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
