# Generated by Django 4.2.5 on 2023-11-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="T1",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("a", models.CharField(blank=True, max_length=10, null=True)),
                ("b", models.CharField(blank=True, max_length=10, null=True)),
                ("c", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="T2",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("d", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "e",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tester.t1",
                        verbose_name="e from T1",
                    ),
                ),
            ],
        ),
    ]
