# Generated by Django 4.2.5 on 2023-11-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "department",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Governorate",
            fields=[
                (
                    "gov",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("location", models.TextField(blank=True, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("discription", models.TextField()),
            ],
        ),
    ]
