# Generated by Django 4.2.5 on 2023-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manpower", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "contract",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(null=True)),
            ],
        ),
    ]
