# Generated by Django 4.2.5 on 2023-11-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_name_photo"),
        ("manpower", "0002_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job_list",
            fields=[
                (
                    "job",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mp_history",
            fields=[
                (
                    "transaction",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("id", models.CharField(max_length=7)),
                ("recipient", models.CharField(max_length=7)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mp_Location",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="manpower.mp_list",
                    ),
                ),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="project.name"
                    ),
                ),
            ],
        ),
    ]
