# Generated by Django 4.2.5 on 2023-11-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_name_photo"),
        ("manpower", "0003_job_list_mp_history_mp_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mp_location",
            name="id",
        ),
        migrations.RemoveField(
            model_name="mp_location",
            name="recipient",
        ),
        migrations.AddField(
            model_name="mp_list",
            name="recipient",
            field=models.ForeignKey(
                default="CP2011",
                on_delete=django.db.models.deletion.CASCADE,
                to="project.name",
            ),
        ),
        migrations.AddField(
            model_name="mp_list",
            name="update",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="mp_list",
            constraint=models.UniqueConstraint(
                fields=("id", "recipient"), name="unique_mp_list"
            ),
        ),
        migrations.DeleteModel(
            name="Mp_Location",
        ),
    ]
