# Generated by Django 4.2.5 on 2023-11-19 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_name_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "manpower",
            "0004_remove_mp_location_id_remove_mp_location_recipient_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMp_list",
            fields=[
                ("id", models.CharField(db_index=True, max_length=7)),
                ("first_name", models.CharField(max_length=20)),
                ("middle_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("update", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        default="CP2011",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="project.name",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical mp_list",
                "verbose_name_plural": "historical mp_lists",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
