# Generated by Django 4.2.5 on 2023-11-19 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_name_photo"),
        ("manpower", "0005_historicalmp_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mp_list",
            name="recipient",
            field=models.ForeignKey(
                default="CP2011",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.name",
            ),
        ),
        migrations.CreateModel(
            name="Mp_Location",
            fields=[
                (
                    "id",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.name"
                    ),
                ),
            ],
        ),
    ]
