# Generated by Django 4.2.5 on 2023-11-20 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manpower", "0007_remove_mp_list_unique_mp_list_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mp_location",
            name="update",
        ),
    ]
