# Generated by Django 4.2.5 on 2023-11-22 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("master", "0001_initial"),
        ("manpower", "0008_remove_mp_location_update"),
    ]

    operations = [
        migrations.CreateModel(
            name="Title_list",
            fields=[
                (
                    "title",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="mp_list",
            options={"ordering": ["-id"]},
        ),
        migrations.RenameField(
            model_name="job_type",
            old_name="job",
            new_name="title",
        ),
        migrations.AddField(
            model_name="historicalmp_list",
            name="birth",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 11, 22, 14, 21, 35, 357519, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmp_list",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="manpower.contract",
            ),
        ),
        migrations.AddField(
            model_name="historicalmp_list",
            name="created",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmp_list",
            name="full_discription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmp_list",
            name="full_name",
            field=models.CharField(
                default="<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalmp_list",
            name="gov",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="master.governorate",
            ),
        ),
        migrations.AddField(
            model_name="historicalmp_list",
            name="hire",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmp_list",
            name="national_id",
            field=models.IntegerField(default=django.utils.timezone.now, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalmp_list",
            name="sex",
            field=models.CharField(
                choices=[("m", "male"), ("f", "female")], default="m", max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mp_list",
            name="birth",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mp_list",
            name="contract",
            field=models.ForeignKey(
                default="a",
                on_delete=django.db.models.deletion.CASCADE,
                to="manpower.contract",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mp_list",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mp_list",
            name="full_discription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mp_list",
            name="full_name",
            field=models.CharField(
                default="<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="mp_list",
            name="gov",
            field=models.ForeignKey(
                default="A",
                on_delete=django.db.models.deletion.CASCADE,
                to="master.governorate",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mp_list",
            name="hire",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mp_list",
            name="national_id",
            field=models.IntegerField(default="A", max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mp_list",
            name="sex",
            field=models.CharField(
                choices=[("m", "male"), ("f", "female")], default="m", max_length=10
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalmp_list",
            name="id",
            field=models.CharField(db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="mp_list",
            name="id",
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.RenameModel(
            old_name="Job_list",
            new_name="Job_type",
        ),
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "mp_code",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("job", models.CharField(max_length=50)),
                ("speciality", models.CharField(default="عام", max_length=50)),
                (
                    "calc",
                    models.CharField(
                        choices=[("d", "direct"), ("i", "indirect")], max_length=10
                    ),
                ),
                (
                    "dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.department",
                    ),
                ),
                (
                    "job_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manpower.job_type",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manpower.title_list",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="historicalmp_list",
            name="code",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="manpower.code",
            ),
        ),
        migrations.AddField(
            model_name="mp_list",
            name="code",
            field=models.ForeignKey(
                default="A",
                on_delete=django.db.models.deletion.CASCADE,
                to="manpower.code",
            ),
            preserve_default=False,
        ),
    ]
