# Generated by Django 4.2.5 on 2023-11-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mp_list",
            fields=[
                (
                    "id",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("middle_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
            ],
        ),
    ]
