# Generated by Django 4.2.5 on 2023-11-22 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("manpower", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mp_list",
        ),
    ]
