# Generated by Django 4.2.5 on 2023-11-22 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("master", "0001_initial"),
        ("project", "0006_alter_name_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("manpower", "0002_delete_mp_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Code",
            fields=[
                (
                    "mp_code",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                ("job", models.CharField(max_length=50)),
                ("speciality", models.CharField(default="عام", max_length=50)),
                (
                    "calc",
                    models.CharField(
                        choices=[("d", "direct"), ("i", "indirect")], max_length=10
                    ),
                ),
                (
                    "dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "contract",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job_type",
            fields=[
                (
                    "title",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mp_history",
            fields=[
                (
                    "transaction",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("id", models.CharField(max_length=7)),
                ("recipient", models.CharField(max_length=7)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Title_list",
            fields=[
                (
                    "title",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mp_Location",
            fields=[
                (
                    "id",
                    models.CharField(max_length=7, primary_key=True, serialize=False),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mp_list",
            fields=[
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("middle_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                (
                    "full_name",
                    models.CharField(
                        default="<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>",
                        max_length=100,
                    ),
                ),
                ("full_discription", models.TextField(blank=True, null=True)),
                ("hire", models.DateField()),
                ("birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=10
                    ),
                ),
                ("national_id", models.IntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("update", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="manpower.code"
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manpower.contract",
                    ),
                ),
                (
                    "gov",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="master.governorate",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalMp_list",
            fields=[
                ("id", models.CharField(db_index=True, max_length=8)),
                ("first_name", models.CharField(max_length=20)),
                ("middle_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                (
                    "full_name",
                    models.CharField(
                        default="<django.db.models.fields.CharField> <django.db.models.fields.CharField> <django.db.models.fields.CharField>",
                        max_length=100,
                    ),
                ),
                ("full_discription", models.TextField(blank=True, null=True)),
                ("hire", models.DateField()),
                ("birth", models.DateField()),
                (
                    "sex",
                    models.CharField(
                        choices=[("m", "male"), ("f", "female")], max_length=10
                    ),
                ),
                ("national_id", models.IntegerField()),
                ("created", models.DateTimeField(blank=True, editable=False)),
                ("update", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "code",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="manpower.code",
                    ),
                ),
                (
                    "contract",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="manpower.contract",
                    ),
                ),
                (
                    "gov",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="master.governorate",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical mp_list",
                "verbose_name_plural": "historical mp_lists",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="code",
            name="job_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manpower.job_type"
            ),
        ),
        migrations.AddField(
            model_name="code",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="manpower.title_list"
            ),
        ),
    ]
