# Generated by Django 4.2.5 on 2023-11-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manpower", "0004_alter_code_calc_alter_contract_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmp_list",
            name="photo",
            field=models.TextField(default="user.jpg", max_length=100),
        ),
        migrations.AddField(
            model_name="mp_list",
            name="photo",
            field=models.ImageField(
                default="user.jpg", upload_to="mp/<django.db.models.fields.CharField>"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmp_list",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mp_list",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
    ]
