# Generated by Django 4.2.5 on 2023-11-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manpower", "0005_historicalmp_list_photo_mp_list_photo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmp_list",
            name="national_id",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="mp_list",
            name="national_id",
            field=models.BigIntegerField(),
        ),
    ]
