# Generated by Django 4.2.5 on 2023-11-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manpower", "0006_alter_historicalmp_list_national_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mp_list",
            name="photo",
            field=models.ImageField(
                default="user.jpg",
                upload_to="mp/users/<django.db.models.fields.CharField>",
            ),
        ),
    ]
