# Generated by Django 4.2.5 on 2023-11-23 10:20

from django.db import migrations, models
import manpower.models


class Migration(migrations.Migration):
    dependencies = [
        ("manpower", "0007_alter_mp_list_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mp_list",
            name="photo",
            field=models.ImageField(
                default="user.jpg", upload_to=manpower.models.upload_path
            ),
        ),
    ]
