# Generated by Django 4.2.5 on 2023-12-10 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0006_alter_name_photo"),
        ("manpower", "0009_alter_mp_list_options_alter_historicalmp_list_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mp_history",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="project.name"
            ),
        ),
        migrations.AlterField(
            model_name="mp_history",
            name="transaction",
            field=models.AutoField(default=7100000, primary_key=True, serialize=False),
        ),
    ]
