# Generated by Django 4.2.5 on 2023-11-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_photo_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="name",
            name="photo",
            field=models.ImageField(
                default="static\\images\\Project\\Cover\\default.jpg",
                upload_to="media/project/%Y/%m/%d/",
            ),
        ),
        migrations.DeleteModel(
            name="Photo",
        ),
    ]
