# Generated by Django 4.2.5 on 2023-11-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_alter_name_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="name",
            name="photo",
            field=models.ImageField(
                default="default.jpg", upload_to="project/%Y/%m/%d/"
            ),
        ),
    ]
